#!/usr/bin/env node

const pgtools = require("pgtools");
require('../env.js');

pgtools.createdb({
  host: process.env.DB_HOST,
  port: process.env.DB_PORT,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD
}, process.env.DB_NAME, (error) => error && console.error(error.message));
